databases:
  - name: shammy_pet
    databaseName: shammy_pet
    user: sharon

services:
  - type: web
    name: shammy_pet
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shammy_pet
          property: connectionString
     